# Name of the workflow

name: Practice Workflow

on:
  # Trigger the workflow on push or pull request events for the "main" branch
  push:
    branches: ["main"]
  workflow_dispatch: # Manual trigger(Colon is necessary for this line)
    
jobs:
  sample_job:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run a simple command
      - name: Run a one-line script
        run: |
          echo "Hello, world!"
          echo "$GITHUB_WORKSPACE"


      # Run a multi-line script
      - name: Run a multi-line script
        run: |
          echo "This is a sample workflow."
          echo "You can add more steps as needed."



